<?php

namespace Slendium\Ocd;

/**
 * Marker interface for database-serializable objects with a {@see Schema}.
 *
 * Entities can implement {@see Entity\Identifiable} to automatically generate a default primary key.
 * When implementing this interface the constructor must have a parameter called `id` with a type that implements {@see Entity\Id}.
 * Further configuration of the ID requires adding the {@see Schema\IdOptions} attribute.
 *
 * Fields are declared as parameters of the constructor of the entity.
 * These parameters are later used to reconstruct an entity from a database record.
 * Parameters can be excluded using the {@see Schema\Exclude} attribute.
 * The {@see Schema\FieldName} attribute overrides the default field name (the parameter name).
 *
 * For compatibility with MongoDB it is not recommended to declare a field named `_id`.
 *
 * ## Example
 *
 * Example of a basic entity with an autogenerated unique ID.
 *
 * ```php
 * final class Product implements Entity, Entity\Identifiable {
 *
 * 	public function __construct(
 *
 * 		#[Override]
 * 		public readonly Entity\Id $id,
 *
 * 		#[Schema\FieldName('NAME_LEGACY')]
 * 		public readonly string $name,
 *
 * 		public readonly int $stock = 0,
 *
 * 		#[Schema\Exclude]
 * 		public float $factor = 1.0,
 *
 * 	) { }
 *
 * }
 * ```
 *
 * @since 1.0
 * @author C. Fahner
 * @copyright Slendium 2026
 */
interface Entity { }
