<?php

namespace Slendium\Ocd;

use Slendium\Ocd\Common\SequentialValue;
use Slendium\Ocd\Common\UniqueIdentifier;

/**
 * A database-serializable object that is uniquely identifiable.
 *
 * Objects are not required to implement this interface to generate a {@see Schema}.
 * In this case the schema won't contain an automatically generated primary key.
 *
 * Fields are declared as parameters of the constructor of the entity.
 * These parameters are later used to reconstruct an entity from a database record.
 * Parameters can be excluded using the {@see Schema\Exclude} attribute.
 * The {@see Schema\FieldName} attribute overrides the default field name (the parameter name).
 *
 * For compatibility with MongoDB it is not recommended to declare a field named `_id`.
 *
 * ## Example
 *
 * Example of a basic entity with an autogenerated unique ID.
 *
 * ```php
 * final class Product implements Entity {
 *
 * 	public function __construct(
 *
 * 		#[Override]
 * 		public readonly UniqueIdentifier $id,
 *
 * 		#[Schema\FieldName('NAME_LEGACY')]
 * 		public readonly string $name,
 *
 * 		public readonly int $stock = 0,
 *
 * 		#[Schema\Exclude]
 * 		public float $factor = 1.0,
 *
 * 	) { }
 *
 * }
 * ```
 *
 * @since 1.0
 * @author C. Fahner
 * @copyright Slendium 2026
 */
interface Entity {

	/** @since 1.0 */
	public UniqueIdentifier|SequentialValue|string|int $id { get; }

}
